const placeholderMottoes = [
  "Even Einstein started with a blank page.",
  "Who said organized wasn't fun?",
  "Ideas live here.",
  "This could be genius.",
  "Write like no one's watching.",
  "Start messy, end brilliant.",
  "Where thoughts become things.",
  "Unleash your inner note-taker.",
  "Type something dangerously smart.",
  "Bold thoughts welcome.",
  "Dream it, jot it, do it.",
  "Future you will thank present you.",
  "Say it like it matters.",
  "Blank page, infinite possibilities.",
  "Notes today, legacy tomorrow.",
  "Chaos, meet clarity.",
  "Greatness begins here.",
  "Keyboard therapy in progress.",
  "Your brain needs this.",
  "Don't let brilliance slip away.",
  "Brain dump central.",
  "Welcome to Idea HQ.",
  "Organize like a legend.",
  "Where thoughts find a home.",
  "This space loves sticky ideas.",
  "The next big thing starts here.",
  "Make memory lane less foggy.",
  "Writing is thinking out loud.",
  "What were you about to forget?",
  "Behold, the thinking zone.",
  "Fill the void (productively).",
  "For thoughts too precious to lose.",
  "Write it before it vanishes.",
  "A digital whisper of genius.",
  "Your daily dose of clarity.",
  "Put your chaos in check.",
  "Scribbles today, strategy tomorrow.",
  "The silence before the storm of ideas.",
  "You're not procrastinating if you're typing.",
  "This app doesn't judge.",
  "Plotting your rise to greatness.",
  "Jot your destiny.",
  "Let the typing therapy begin.",
  "You've got notes to write and worlds to change.",
  "Don't just think it—note it.",
  "Tiny thoughts, big impact.",
  "Messy notes = brilliant mind.",
  "From 'just a thought' to 'wow.'",
  "Let the randomness begin.",
  "Where half-baked ideas get full attention.",
  "A safe place for rogue brilliance.",
  "No judgment, just genius.",
  "Your thoughts deserve a spotlight.",
  "Get it out of your head.",
  "Mental clutter? Handle it here.",
  "Notes so smart, they'll need sunglasses.",
  "This space believes in you.",
  "Today's thoughts, tomorrow's memoir.",
  "The paper trail of brilliance starts now.",
  "Notes, but make them epic.",
  "Every click a spark.",
  "Capture the moment before it runs.",
  "Don't be afraid to ramble.",
  "This is where the magic brews.",
  "Free your mind—one keystroke at a time.",
  "Ideas in progress.",
  "Document your rise.",
  "Smart thoughts ahead.",
  "The lab for your mental experiments.",
  "A playground for grown-up thoughts.",
  "No bad ideas—just unedited genius.",
  "Type it like you mean it.",
  "Noted and loaded.",
  "Where brilliance takes shape.",
  "Scribble boldly.",
  "Note it now, thank me later.",
  "Catch your thoughts before they fly away.",
  "Start here, end in history books.",
  "Brainstorm bunker online.",
  "Welcome, thought explorer.",
  "The thought incubator.",
  "Typist of destiny.",
  "Write here, right now.",
  "Inbox for your brainwaves.",
  "Placeholder, not place-forgetter.",
  "Creative cloud incoming.",
  "You're one note away from a breakthrough.",
  "Note vibes only.",
  "Think loud, type proud.",
  "Document the chaos beautifully.",
  "Memory fuel incoming...",
  "Breakthrough loading…",
  "Ctrl + thoughts + enter",
  "Forget me not.",
  "Embrace the scribble.",
  "Fewer blanks, more brilliance.",
  "Collect your thoughts like treasures.",
  "Notes are how legends start.",
  "Scribble something scandalously smart.",
  "What if this is the big idea?",
  "Keep typing. You're onto something.",
  "Note like a novelist.",
  "This text box is secretly a launchpad.",
  "Mind-space in session.",
];

export function randomMotto() {
  const rndNum = Math.floor(Math.random() * 100);
  return placeholderMottoes[rndNum];
}
