import "./fanta.css";
import "./globals.css";
import Head from "./head";

export const metadata = {
  title: "Echoes | Notes of Yours",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body>
        <div id="app">{children}</div>
        <div id="portal"></div>
      </body>
    </html>
  );
}
